on:
  push:
    branches: [feature/add_git_template]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linter:
    if: ${{ github.event_name == 'pull_request' }}
    name: Linter
    uses: sbgisen/.github/.github/workflows/linter_ros_package.yaml@main
  build:
    needs: linter
    if: ${{ !failure() }}
    name: Build
    uses: sbgisen/.github/.github/workflows/ros-build.yml@main
    secrets:
      ssh_key: ${{ secrets.GISEN_ROBO_GIT }}
      known_hosts: ${{ secrets.KNOWN_HOSTS }}
  test:
    needs: linter
    if: ${{ !failure() }}
    name: Test
    uses: sbgisen/.github/.github/workflows/ros-test.yml@main
  release-drafter:
    name: Release drafter
    uses: sbgisen/.github/.github/workflows/release-drafter.yml@main
